# Generated by Django 4.2.1 on 2023-11-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_alter_mark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
